name: Publish SidekickNet NuGet packages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x.x
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish with dotnet
      run: dotnet nuget push --skip-duplicate "**/SidekickNet.*.nupkg" -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_API_KEY }}
#    - name: Publish symbols with dotnet
#      run: dotnet nuget push "bin/Release/SidekickNet.*.snupkg" --source "https://nuget.pkg.github.com/cnshenj/index.json"
